version: 2

sources:
  - name: jaffle_shop
    description: 'Elvis first use of source'
    database: raw
    schema: jaffle_shop
    tables:
      - name: orders
      - name: customers

  - name: jaffle_shop_stripe
    description: 'Elvis first use of source with stripe'
    database: raw
    schema: stripe
    tables:
      - name: payment